DROP TABLE IF EXISTS VST_AUTHRT;
CREATE TABLE VST_AUTHRT
(
    AUTHRT_ID     BIGINT NOT NULL AUTO_INCREMENT COMMENT '권한 아이디' PRIMARY KEY,
    AUTHRT_CD     VARCHAR(30) NOT NULL COMMENT '권한코드' UNIQUE,
    AUTHRT_NM       VARCHAR(60) NOT NULL COMMENT '권한명',
    AUTHRT_EXPLN       VARCHAR(200) NULL COMMENT '권한설명',
    DEL_PSBLTY_YN CHAR(1) NULL COMMENT '삭제가능여부',
    FRST_RGTR_ID  BIGINT NULL COMMENT '최초등록자 아이디',
    FRST_REG_DT   DATETIME    NULL COMMENT '최초등록일시',
    LAST_MDFR_ID  BIGINT NULL COMMENT '최종수정자 아이디',
    LAST_MDFCN_DT DATETIME NULL COMMENT '최종수정일시'
) COMMENT = '권한';

DROP TABLE IF EXISTS VST_PROGRM;
CREATE TABLE VST_PROGRM
(
    PROGRM_ID  BIGINT       NOT NULL AUTO_INCREMENT COMMENT '프로그램ID' PRIMARY KEY,
    PROGRM_NM  VARCHAR(60)  NOT NULL COMMENT '프로그램명',
    PROGRM_DC  VARCHAR(200) NULL COMMENT '프로그램설명',
    PROGRM_URL VARCHAR(100) NOT NULL COMMENT '프로그램URL',
    FRST_REGISTER_ID  BIGINT NULL COMMENT '최초등록자ID',
    FRST_REGIST_DT    DATETIME NULL COMMENT '최초등록일시',
    LAST_UPDUSR_ID    BIGINT NULL COMMENT '최종수정자ID',
    LAST_UPDT_DT      DATETIME NULL COMMENT '최종수정일시'
) COMMENT = '프로그램';

DROP TABLE IF EXISTS VST_POPUP;
CREATE TABLE VST_POPUP
(
    POPUP_ID          INTEGER       NOT NULL AUTO_INCREMENT COMMENT '팝업ID',
    POPUP_NM          VARCHAR(60)    NOT NULL COMMENT '팝업명',
    SORT_ORDR         DECIMAL(8, 0)  NOT NULL COMMENT '정렬순서',
    URL               VARCHAR(200) NULL COMMENT 'URL',
    POPUP_WIDTH_LC    VARCHAR(20)    NOT NULL COMMENT '팝업가로위치',
    POPUP_WIDTH_SIZE  DECIMAL(10, 0) NOT NULL COMMENT '팝업가로사이즈',
    POPUP_VRTICL_LC   VARCHAR(20)    NOT NULL COMMENT '팝업세로위치',
    POPUP_VRTICL_SIZE DECIMAL(10, 0) NOT NULL COMMENT '팝업세로사이즈',
    NTCE_AT           CHAR(1)        NOT NULL DEFAULT 'Y' COMMENT '게시여부',
    NTCE_BGNDE        DATETIME       NOT NULL COMMENT '게시시작일',
    NTCE_ENDDE        DATETIME       NOT NULL COMMENT '게시종료일',
    STOPVEW_SETUP_AT  CHAR(1) NULL DEFAULT 'Y' COMMENT '그만보기설정여부',
    FRST_REGISTER_ID  BIGINT    NOT NULL COMMENT '최초등록자ID',
    FRST_REGIST_DT    DATETIME       NOT NULL COMMENT '최초등록일시',
    LAST_UPDUSR_ID    BIGINT NULL COMMENT '최종수정자ID',
    LAST_UPDT_DT      DATETIME NULL COMMENT '최종수정일시',
    PRIMARY KEY (POPUP_ID)
) COMMENT = '팝업';

DROP TABLE IF EXISTS VST_NTT;
CREATE TABLE VST_NTT
(
    NTT_ID           INTEGER        NOT NULL AUTO_INCREMENT COMMENT '게시글ID',
    BBS_ID           VARCHAR(20)    NOT NULL COMMENT '게시판ID',
    PARNTSCTT_ID     VARCHAR(20) NULL COMMENT '부모글ID',
    NTT_SJ           VARCHAR(2000)  NOT NULL COMMENT '게시글제목',
    NTT_CN           MEDIUMTEXT     NOT NULL COMMENT '게시글내용',
    RDCNT            DECIMAL(10, 0) NOT NULL COMMENT '조회수',
    SECRET_AT        CHAR(1)        NOT NULL COMMENT '비밀글여부',
    NOTICE_AT        CHAR(1)        NOT NULL COMMENT '공지여부',
    USE_AT           CHAR(1)        NOT NULL COMMENT '사용여부',
    FRST_REGISTER_ID BIGINT NULL COMMENT '최초등록ID',
    FRST_REGIST_DT   DATETIME       NOT NULL COMMENT '최초등록일시',
    LAST_UPDUSR_ID   BIGINT NULL COMMENT '최종수정자ID',
    LAST_UPDT_DT     DATETIME NULL COMMENT '최종수정일시',
    WRTER_NM         VARCHAR(50)    NOT NULL COMMENT '작성자명',
    PASSWORD         VARCHAR(200) NULL COMMENT '비밀번호',
    THUMB_URL        VARCHAR(50) NULL COMMENT '썸네일URL',
    PRIMARY KEY (NTT_ID)
) COMMENT = '게시글';

DROP TABLE IF EXISTS VST_MBR_AUTHRT;
CREATE TABLE VST_MBR_AUTHRT
(
    MBR_ID    BIGINT NOT NULL COMMENT '회원 아이디',
    AUTHRT_ID BIGINT NOT NULL COMMENT '권한 아이디',
    PRIMARY KEY (MBR_ID, AUTHRT_ID)
) COMMENT = '회원권한';

DROP TABLE IF EXISTS VST_MENU_AUTHRT;
CREATE TABLE VST_MENU_AUTHRT
(
    MENU_ID BIGINT NOT NULL COMMENT '메뉴 아이디',
    AUTHRT_ID BIGINT NOT NULL COMMENT '권한 아이디',
    PRIMARY KEY (MENU_ID, AUTHRT_ID)
) COMMENT = '메뉴권한';

DROP TABLE IF EXISTS VST_MENU;
CREATE TABLE VST_MENU
(
    MENU_ID       BIGINT      NOT NULL AUTO_INCREMENT COMMENT '메뉴 아이디' PRIMARY KEY,
    ID            VARCHAR(20) NULL COMMENT '아이디' UNIQUE,
    MENU_NM       VARCHAR(60) NOT NULL COMMENT '메뉴명',
    UPPER_MENU_ID BIGINT NULL COMMENT '상위메뉴 아이디',
    MENU_ORDR     DECIMAL(5) NULL COMMENT '메뉴순서',
    MENU_TY       VARCHAR(10) NULL COMMENT '메뉴타입',
    MENU_SE       VARCHAR(10) NULL COMMENT '메뉴구분',
    MENU_DP       DECIMAL(5) NULL COMMENT '메뉴DEPTH',
    CNTC_ID       VARCHAR(20) NULL COMMENT '연계ID',
    URL           VARCHAR(200) NULL COMMENT 'URL',
    USE_AT        CHAR(1) NULL COMMENT '사용여부',
    GNB_AT        CHAR(1) NULL COMMENT 'GNB여부'
) COMMENT = '메뉴';

DROP TABLE IF EXISTS VST_LGN_LOG;
CREATE TABLE VST_LGN_LOG
(
    ACSR_NM   VARCHAR(50) NOT NULL COMMENT '접속자명',
    ACSR_ID   BIGINT NOT NULL COMMENT '접속자 아이디',
    ACSR_IP_ADDR   VARCHAR(15) NULL COMMENT '접속자IP주소',
    CNTN_SE   CHAR(1) NULL COMMENT '접속구분 (I: 로그인, O: 로그아웃)',
    ACSR_OS_NM   VARCHAR(20) COMMENT '접속자 운영체제명',
    CNTN_DT  DATETIME NULL COMMENT '접속일시'
) COMMENT = '로그인로그';

DROP TABLE IF EXISTS VST_CNTNTS_HIST;
CREATE TABLE VST_CNTNTS_HIST
(
    CNTNTS_HIST_ID INTEGER       NOT NULL AUTO_INCREMENT COMMENT '콘텐츠이력ID',
    CNTNTS_ID      VARCHAR(20)  NOT NULL COMMENT '콘텐츠ID',
    CNTNTS_NM      VARCHAR(100) NOT NULL COMMENT '콘텐츠명',
    HIST_SE_CODE   CHAR(6)      NOT NULL COMMENT '이력구분코드',
    LAST_UPDUSR_ID VARCHAR(20) NULL COMMENT '최종수정자ID',
    LAST_UPDT_DT   DATETIME NULL COMMENT '최종수정일시',
    PRIMARY KEY (CNTNTS_HIST_ID)
) COMMENT = '콘텐츠이력';

DROP TABLE IF EXISTS VST_CNTNTS;
CREATE TABLE VST_CNTNTS
(
    CNTNTS_ID        INTEGER       NOT NULL AUTO_INCREMENT COMMENT '콘텐츠ID',
    CNTNTS_NM        VARCHAR(100) NOT NULL COMMENT '콘텐츠명',
    CNTNTS_CN        MEDIUMTEXT   NOT NULL COMMENT '콘텐츠내용',
    CNTNTS_DC        VARCHAR(250) NOT NULL COMMENT '콘텐츠설명',
    FRST_REGISTER_ID BIGINT NULL COMMENT '최초등록자ID',
    FRST_REGIST_DT   DATETIME NULL COMMENT '최초등록일시',
    LAST_UPDUSR_ID   BIGINT NULL COMMENT '최종수정자ID',
    LAST_UPDT_DT     DATETIME NULL COMMENT '최종수정일시',
    PRIMARY KEY (CNTNTS_ID)
) COMMENT = '콘텐츠';

DROP TABLE IF EXISTS VST_BBS;
CREATE TABLE VST_BBS
(
    BBS_ID           BIGINT       NOT NULL AUTO_INCREMENT COMMENT '게시판ID',
    BBS_NM           VARCHAR(255)  NOT NULL COMMENT '게시판명',
    BBS_TY_CODE      CHAR(20)      NOT NULL COMMENT '게시판유형코드',
    PERM_EXTSN       VARCHAR(300) COMMENT '허용 확장자',
    FILE_ATCH_SIZE   DECIMAL(3, 0) NOT NULL COMMENT '파일첨부용량',
    FILE_ATCH_CO     DECIMAL(3, 0) NULL COMMENT '파일첨부개수',
    SECRET_USE_AT    CHAR(1)       NOT NULL COMMENT '비밀글 사용 여부',
    ANSWER_AT        CHAR(1)       NOT NULL COMMENT '댓글사용여부',
    REPLY_AT         CHAR(1)       NOT NULL COMMENT '답변사용여부',
    USE_AT           CHAR(1)       NOT NULL COMMENT '사용여부',
    FRST_REGISTER_ID BIGINT   NOT NULL COMMENT '최초등록ID',
    FRST_REGIST_DT   DATETIME      NOT NULL COMMENT '최초등록일시',
    LAST_UPDUSR_ID   BIGINT NULL COMMENT '최종수정자ID',
    LAST_UPDT_DT     DATETIME NULL COMMENT '최종수정일시',
    PRIMARY KEY (BBS_ID)
) COMMENT = '게시판';

DROP TABLE IF EXISTS VST_BBS_AUTHRT;
CREATE TABLE VST_BBS_AUTHRT
(
    BBS_ID      BIGINT NOT NULL COMMENT '게시판 아이디',
    AUTHRT_ID   BIGINT NOT NULL COMMENT '권한 아이디',
    AUTHOR_LIST VARCHAR(50) NOT NULL COMMENT '권한목록',
    PRIMARY KEY (BBS_ID, AUTHRT_ID)
) COMMENT = '게시판권한';

DROP TABLE IF EXISTS VST_BANNER;
CREATE TABLE VST_BANNER
(
    BANNER_ID        INTEGER       NOT NULL AUTO_INCREMENT COMMENT '배너ID',
    BANNER_NM        VARCHAR(60)   NOT NULL COMMENT '배너명',
    REFLCT_AT        CHAR(1)       NOT NULL COMMENT '반영여부',
    URL              VARCHAR(200) NULL COMMENT 'URL',
    SORT_ORDR        DECIMAL(8, 0) NOT NULL COMMENT '정렬순서',
    BANNER_SE_CODE   CHAR(6)       NOT NULL COMMENT '배너구분코드',
    FRST_REGISTER_ID BIGINT   NOT NULL COMMENT '최초등록자ID',
    FRST_REGIST_DT   DATETIME      NOT NULL COMMENT '최초등록일시',
    LAST_UPDUSR_ID   BIGINT NULL COMMENT '최종수정자ID',
    LAST_UPDT_DT     DATETIME NULL COMMENT '최종수정일시',
    NTCE_BGNDE       DATETIME      NOT NULL COMMENT '게시시작일',
    NTCE_ENDDE       DATETIME      NOT NULL COMMENT '게시종료일',
    DC               VARCHAR(50) NULL COMMENT '설명',
    NEW_BRWS_AT      CHAR(1)       NOT NULL COMMENT '새창여부',
    PRIMARY KEY (BANNER_ID)
) COMMENT = '배너';

DROP TABLE IF EXISTS VST_ATCHFILE;
CREATE TABLE VST_ATCHFILE
(
    ATCH_FILE_ID     INTEGER       NOT NULL AUTO_INCREMENT COMMENT '첨부파일ID',
    FILE_STRE_COURS  VARCHAR(2000) NOT NULL COMMENT '파일저장경로',
    STRE_FILE_NM     VARCHAR(255)  NOT NULL COMMENT '저장파일명',
    ORIGNL_FILE_NM   VARCHAR(255)  NOT NULL COMMENT '원본파일명',
    FILE_EXTSN       VARCHAR(255)  NOT NULL COMMENT '파일확장자',
    FILE_SIZE        DECIMAL(8)    NOT NULL COMMENT '파일크기',
    UPPER_ID         VARCHAR(20) NULL COMMENT '상위ID',
    USE_AT           CHAR(1)       NOT NULL DEFAULT 'Y' COMMENT '사용여부',
    FILE_SE          VARCHAR(20) NULL COMMENT '파일구분',
    FRST_REGISTER_ID BIGINT   NOT NULL COMMENT '최초등록자ID',
    FRST_REGIST_DT   DATETIME NULL COMMENT '최초등록일시',
    PRIMARY KEY (ATCH_FILE_ID)
) COMMENT = '첨부파일';

DROP TABLE IF EXISTS VST_ANSWER;
CREATE TABLE VST_ANSWER
(
    ANSWER_ID        INTEGER      NOT NULL AUTO_INCREMENT  COMMENT '댓글ID',
    NTT_ID           INTEGER  NOT NULL COMMENT '게시글ID',
    ANSWER_CN        VARCHAR(200) NOT NULL COMMENT '댓글내용',
    USE_AT           CHAR(1)      NOT NULL COMMENT '사용여부',
    WRTER_NM         VARCHAR(50) NULL COMMENT '작성자명',
    PASSWORD         VARCHAR(200) NULL COMMENT '비밀번호',
    FRST_REGISTER_ID BIGINT NULL COMMENT '최초등록ID',
    FRST_REGIST_DT   DATETIME     NOT NULL COMMENT '최초등록일시',
    LAST_UPDUSR_ID   BIGINT NULL COMMENT '최종수정자ID',
    LAST_UPDT_DT     DATETIME NULL COMMENT '최종수정일시',
    PRIMARY KEY (ANSWER_ID)
) COMMENT = '댓글';

DROP TABLE IF EXISTS VST_ACCESSIP;
CREATE TABLE VST_ACCESSIP
(
    IP_ID            BIGINT       NOT NULL AUTO_INCREMENT COMMENT '아이피ID' PRIMARY KEY,
    IP_ADRES         VARCHAR(255) NOT NULL COMMENT '아이피주소',
    IP_DC            VARCHAR(255) NULL COMMENT '아이피설명',
    FRST_REGISTER_ID BIGINT NULL COMMENT '최초등록자ID',
    FRST_REGIST_DT   DATETIME NULL COMMENT '최초등록일시',
    LAST_UPDUSR_ID   BIGINT NULL COMMENT '최종수정자ID',
    LAST_UPDT_DT     DATETIME NULL COMMENT '최종수정일시'
) COMMENT = '접근IP';

DROP TABLE IF EXISTS VST_MBR;
CREATE TABLE VST_MBR
(
    MBR_ID         BIGINT       NOT NULL AUTO_INCREMENT COMMENT '회원 아이디' PRIMARY KEY,
    UUID           CHAR(36)     NOT NULL COMMENT 'UUID' UNIQUE,
    ID             VARCHAR(20)  NOT NULL COMMENT '아이디' UNIQUE,
    PSWD           VARCHAR(200) NOT NULL COMMENT '비밀번호',
    MBR_NM         VARCHAR(50)  NOT NULL COMMENT '회원명',
    EML_ADDR       VARCHAR(320) NULL COMMENT '이메일 주소',
    MBL_TELNO      VARCHAR(20) NULL COMMENT '휴대전화번호',
    FXNO           VARCHAR(20) NULL COMMENT '팩스번호',
    ZIP            VARCHAR(6) NULL COMMENT '우편번호',
    ADDR           VARCHAR(200) NULL COMMENT '주소',
    DADDR          VARCHAR(200) NULL COMMENT '상세주소',
    LGN_LCK_YN     CHAR(1)      NOT NULL DEFAULT 'N' COMMENT '로그인잠금여부',
    LGN_FAIL_NMTM  DECIMAL(3)   NOT NULL DEFAULT 0 COMMENT '로그인실패횟수',
    FRST_RGTR_ID   BIGINT NULL COMMENT '최초등록자 아이디',
    FRST_REG_DT    DATETIME NULL COMMENT '최초등록일시',
    LAST_MDFR_ID   BIGINT NULL COMMENT '최종수정자 아이디',
    LAST_MDFCN_DT  DATETIME NULL COMMENT '최종수정일시',
    STTS_CD        CHAR(1)      NOT NULL DEFAULT 'P' COMMENT '상태코드',
    DVC_PUSH_TOKEN VARCHAR(255) NULL COMMENT '디바이스 푸시 토큰'
) COMMENT = '회원';

DROP TABLE IF EXISTS VST_CMMNCODE;
CREATE TABLE VST_CMMNCODE
(
    CODE_ID        BIGINT      NOT NULL AUTO_INCREMENT COMMENT '코드ID' PRIMARY KEY,
    UPPER_CODE_ID  BIGINT NULL COMMENT '상위코드ID',
    CODE           VARCHAR(20) NULL COMMENT '코드' UNIQUE,
    CODE_NM        VARCHAR(20) NOT NULL COMMENT '코드명',
    CODE_ORDR      DECIMAL(5) NULL COMMENT '코드순서',
    CODE_DEPTH     DECIMAL(5) NULL COMMENT '코드 DEPTH',
    USE_YN         CHAR(1) DEFAULT 'Y' NULL COMMENT '사용여부',
    SYSTEM_CODE_YN CHAR(1) DEFAULT 'N' NULL COMMENT '시스템코드여부',
    FRST_RGTR_ID   BIGINT NULL COMMENT '최초등록자 아이디',
    FRST_REG_DT    DATETIME NULL COMMENT '최초등록일시',
    LAST_MDFR_ID   BIGINT NULL COMMENT '최종수정자 아이디',
    LAST_MDFCN_DT  DATETIME NULL COMMENT '최종수정일시'
) COMMENT = '공통코드';

DROP TABLE IF EXISTS VST_PUSH_LOG;
CREATE TABLE VST_PUSH_LOG
(
    PUSH_LOG_ID   BIGINT NOT NULL AUTO_INCREMENT COMMENT '푸시로그ID' PRIMARY KEY,
    MESSAGE_TITLE VARCHAR(20) NULL COMMENT '메시지 제목',
    MESSAGE_BODY  VARCHAR(100) NULL COMMENT '메시지 내용',
    TOKENS        TEXT COMMENT '토큰',
    SENDER        BIGINT NULL COMMENT '발송자',
    SENT_COUNT    INT NULL COMMENT '발송 수',
    SUCCESS_COUNT    INT NULL COMMENT '성공 수',
    FAILED_COUNT  INT NULL COMMENT '실패 수',
    SENT_AT       DATETIME NULL COMMENT '발송일시'
) COMMENT = 'PUSH 로그';

CREATE TABLE IF NOT EXISTS MBR_SNS (
                                       SNS_ID  BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'SNS 아이디' PRIMARY KEY,
                                       MBER_ID BIGINT       NOT NULL COMMENT '회원 아이디',
                                       EML_ADDR VARCHAR(320) NULL COMMENT '이메일 주소',
                                       PROVIDER VARCHAR(16) NOT NULL COMMENT '제공자',
                                       PROVIDER_ID VARCHAR(16) NOT NULL COMMENT '제공자 ID',
                                       REG_DT  DATETIME NULL COMMENT '최초등록일시'
);